### PR TITLE
DEP Add silverstripe/dynamodb

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-dynamodb/issues/45

Unit test failures are existing - recent 5.0 run - https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/4130292070

### CODE REVIEW

**Comment by GuySartorelli** [comment]
I assume this is draft pending the PR being merged?

**Comment by emteknetnz** [comment]
Probably don't merge this, don't think it works on SCPS

**Comment by GuySartorelli** [comment]
Does scps even have a dynamo db instance? If not, it probably also doesn't have the env var needed for this module to kick in so it shouldn't affect anything.

**Comment by emteknetnz** [comment]
OK - issue with SCPS was [hybridsessions](https://github.com/silverstripe/silverstripe-hybridsessions/pull/83) - can confirm that this can be deployed to SCPS alongside hybridsessions.  dynnamodb will do nothing though it means it'll get released via cow

**Review by GuySartorelli — APPROVED** [review]
CI failures are unrelated.

**Pull request merged**
