### PR TITLE
MNT Move graphql tests out of recipe-cms

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-admin/issues/1799

### CODE REVIEW

**Review by GuySartorelli — APPROVED** [review]
LGTM, will merge once the other PRs are ready

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Actually just noticed. Don't we need to add graphql do the recipe-kitchen-sink deps in composer.json?

**Comment by emteknetnz** [comment]
Yes :-) Added

**Review by GuySartorelli — APPROVED** [review]
re-approved

**Pull request merged**
